<?php
/**
 * Plugin Name: Shahr Index Control
 * Description: Controls indexing and canonical behavior for parameterized URLs to reduce indexing bloat.
 * Version: 1.0.0
 * Author: Site SEO Automation
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Determine whether current request should be marked noindex based on query parameters.
 *
 * @return bool
 */
function shahr_index_control_should_noindex() {
    if ( is_admin() ) {
        return false;
    }

    if ( empty( $_GET ) ) {
        return false;
    }

    $disallowed_keys   = array( 'add-to-cart', 'per_page', 'per_row', 'shop_view', 'orderby', 'min_price', 'max_price', 's', 'feed', 'cms_block', 'gclid', 'fbclid' );
    $disallowed_prefix = array( 'utm_', 'filter_', 'query_type_' );

    foreach ( $_GET as $key => $value ) {
        if ( in_array( $key, $disallowed_keys, true ) ) {
            return true;
        }

        foreach ( $disallowed_prefix as $prefix ) {
            if ( strpos( $key, $prefix ) === 0 ) {
                return true;
            }
        }
    }

    return false;
}

/**
 * Output meta robots noindex tag when necessary.
 */
function shahr_index_control_output_noindex() {
    if ( ! shahr_index_control_should_noindex() ) {
        return;
    }

    echo "<meta name=\"robots\" content=\"noindex,follow\">\n";
}
add_action( 'wp_head', 'shahr_index_control_output_noindex', 1 );

/**
 * Return the canonical URL without query parameters.
 *
 * @return string|false
 */
function shahr_index_control_get_clean_canonical_url() {
    if ( is_admin() || empty( $_SERVER['REQUEST_URI'] ) ) {
        return false;
    }

    $path = strtok( wp_unslash( $_SERVER['REQUEST_URI'] ), '?' );
    $url  = home_url( $path );

    return $url;
}

/**
 * Filter Yoast canonical to strip query parameters.
 *
 * @param string $canonical Canonical URL generated by Yoast.
 *
 * @return string
 */
function shahr_index_control_filter_wpseo_canonical( $canonical ) {
    if ( empty( $_SERVER['QUERY_STRING'] ) ) {
        return $canonical;
    }

    $clean = shahr_index_control_get_clean_canonical_url();

    return $clean ? $clean : $canonical;
}
add_filter( 'wpseo_canonical', 'shahr_index_control_filter_wpseo_canonical' );

/**
 * Filter Rank Math canonical to strip query parameters.
 *
 * @param string $canonical Canonical URL generated by Rank Math.
 *
 * @return string
 */
function shahr_index_control_filter_rankmath_canonical( $canonical ) {
    if ( empty( $_SERVER['QUERY_STRING'] ) ) {
        return $canonical;
    }

    $clean = shahr_index_control_get_clean_canonical_url();

    return $clean ? $clean : $canonical;
}
add_filter( 'rank_math/frontend/canonical', 'shahr_index_control_filter_rankmath_canonical' );

/**
 * Fallback canonical output if no SEO plugin is active.
 */
function shahr_index_control_output_fallback_canonical() {
    if ( is_admin() || empty( $_SERVER['QUERY_STRING'] ) ) {
        return;
    }

    if ( defined( 'WPSEO_VERSION' ) || class_exists( 'RankMath' ) ) {
        return;
    }

    $clean = shahr_index_control_get_clean_canonical_url();

    if ( $clean ) {
        printf( "<link rel=\"canonical\" href=\"%s\">\n", esc_url( $clean ) );
    }
}
add_action( 'wp_head', 'shahr_index_control_output_fallback_canonical', 2 );

/**
 * Add noindex for author and tag archives for improved hygiene when Yoast SEO is active.
 *
 * @param string $robots Robots directives.
 *
 * @return string
 */
function shahr_index_control_noindex_archives( $robots ) {
    if ( is_admin() ) {
        return $robots;
    }

    if ( is_author() || is_tag() ) {
        return 'noindex,follow';
    }

    return $robots;
}
add_filter( 'wpseo_robots', 'shahr_index_control_noindex_archives' );
add_filter( 'rank_math/frontend/robots', 'shahr_index_control_noindex_archives' );
